### ISSUE TITLE
画面設計書

### ISSUE THREAD

**Issue by Nagata0110** [Kyospla/abcc_system_sd3e_grpA#2]
井浦：プロフィール画面、プロフィール修正画面、新規登録画面
諌山：投稿画面、投稿履歴画面、返信画面
永田：ログイン画面、ログイン完了画面、トップ画面、検索結果画面

終わったらここに返信してください。

**Comment by Nagata0110** [comment]
井浦・永田　画面レイアウト完了
画面一覧作成に取り掛かっています。

**Comment by Nagata0110** [comment]
### 画面遷移図　役割分担
Excelファイル

- 井浦：G1
- 永田：G2
- 諌山：G3

各自、5月2日までの完成を目指してください。

**Comment by Nagata0110** [comment]
画面一覧表は井浦・永田で作成し終わりました。残りは、画面遷移図を作成してください。
画面遷移図　G2　永田　終わりました。

**Comment by 2101132** [comment]
画面遷移図　G１　井浦　終わりました。
