### ISSUE TITLE
データモデル設計書(リレーションシップ情報について) 

### ISSUE THREAD

**Issue by 2101216** [Kyospla/abcc_system_sd3e_grpA#7]
データモデル設計書のエンティティ定義書のリレーションシップ情報(FK側)、リレーションシップ情報(PK側)の書き方が分からないので、教えてください。

**Comment by Nagata0110** [comment]
usersの場合
PK側
No カラムリスト　          参照元エンティティ名　        参照元カラム
**1                   ユーザーID(user_id)　コメント情報(comments)       ユーザーID(user_id)**

FK側も同じように書く
